using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace AchEngine.Editor.Table
{
    public static class TableCodeGenerator
    {
        private static readonly Dictionary<string, string> TypeMap = new()
        {
            { "int", "int" },
            { "float", "float" },
            { "string", "string" },
            { "bool", "bool" },
            { "long", "long" },
            { "double", "double" },
            { "int[]", "int[]" },
            { "float[]", "float[]" },
            { "string[]", "string[]" },
            { "bool[]", "bool[]" },
        };

        public struct ColumnInfo
        {
            public string Name;
            public string Type;
            public int Index;
        }

        public static List<ColumnInfo> ParseSchema(List<string[]> csvRows)
        {
            if (csvRows.Count < 2)
                return new List<ColumnInfo>();

            var names = csvRows[0];
            var types = csvRows[1];
            var columns = new List<ColumnInfo>();

            for (int i = 0; i < names.Length && i < types.Length; i++)
            {
                var name = names[i].Trim();
                var type = types[i].Trim().ToLower();

                if (string.IsNullOrEmpty(name) || name.StartsWith("#"))
                    continue;

                if (!TypeMap.ContainsKey(type))
                {
                    Debug.LogWarning($"[TableLoader] 吏?먰븯吏 ?딅뒗 ???'{type}' (而щ읆: {name}). string?쇰줈 ?泥댄빀?덈떎.");
                    type = "string";
                }

                columns.Add(new ColumnInfo
                {
                    Name = name,
                    Type = TypeMap[type],
                    Index = i
                });
            }

            return columns;
        }

        public static string GenerateDataClass(string className, List<ColumnInfo> columns)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by AchEngine TableLoader. DO NOT MODIFY.");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using AchEngine.Table;");
            sb.AppendLine("#if ACHENGINE_MEMORYPACK");
            sb.AppendLine("using MemoryPack;");
            sb.AppendLine("#endif");
            sb.AppendLine();
            sb.AppendLine("[Serializable]");
            sb.AppendLine("#if ACHENGINE_MEMORYPACK");
            sb.AppendLine("[MemoryPackable]");
            sb.AppendLine("#endif");
            sb.AppendLine($"public partial class {className} : ITableData");
            sb.AppendLine("{");

            for (int i = 0; i < columns.Count; i++)
            {
                var col = columns[i];
                sb.AppendLine("#if ACHENGINE_MEMORYPACK");
                sb.AppendLine($"    [MemoryPackOrder({i})]");
                sb.AppendLine("#endif");
                sb.AppendLine($"    public {col.Type} {col.Name} {{ get; set; }}");
                if (i < columns.Count - 1)
                    sb.AppendLine();
            }

            if (!columns.Any(c => c.Name == "Id"))
            {
                sb.AppendLine();
                sb.AppendLine("#if ACHENGINE_MEMORYPACK");
                sb.AppendLine("    [MemoryPackIgnore]");
                sb.AppendLine("#endif");
                sb.AppendLine("    int ITableData.Id => 0;");
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string GenerateLoaderClass(List<(string className, string sheetName)> tables)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by AchEngine TableLoader. DO NOT MODIFY.");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using AchEngine.DI;");
            sb.AppendLine("using AchEngine.Table;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("#if ACHENGINE_MEMORYPACK");
            sb.AppendLine("using MemoryPack;");
            sb.AppendLine("#endif");
            sb.AppendLine();
            sb.AppendLine("public static class TableLoaderGenerated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Resources ?대뜑?먯꽌 紐⑤뱺 ?뚯씠釉붿쓣 濡쒕뱶?⑸땲??");
            sb.AppendLine("    /// TableManager ?뺤쟻 ?뚯궗???먮뒗 ITableService(VContainer)瑜??듯빐 ?ъ슜?????덉뒿?덈떎.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static void LoadAll(string resourceFolder = \"Tables\")");
            sb.AppendLine("    {");

            foreach (var (className, _) in tables)
            {
                sb.AppendLine($"        {{");
                sb.AppendLine($"            var asset = Resources.Load<TextAsset>($\"{{resourceFolder}}/{className}\");");
                sb.AppendLine($"            if (asset != null)");
                sb.AppendLine($"                TableManager.Load<{className}>(asset);");
                sb.AppendLine($"            else");
                sb.AppendLine($"                Debug.LogWarning(\"[TableLoader] '{className}' ?곗씠???뚯씪??李얠쓣 ???놁뒿?덈떎.\");");
                sb.AppendLine($"        }}");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// ITableService瑜?吏곸젒 吏?뺥븯??濡쒕뱶?⑸땲??(VContainer 二쇱엯??.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static void LoadAll(ITableService service, string resourceFolder = \"Tables\")");
            sb.AppendLine("    {");

            foreach (var (className, _) in tables)
            {
                sb.AppendLine($"        {{");
                sb.AppendLine($"            var asset = Resources.Load<TextAsset>($\"{{resourceFolder}}/{className}\");");
                sb.AppendLine($"            if (asset != null)");
                sb.AppendLine($"                service.Load<{className}>(asset);");
                sb.AppendLine($"            else");
                sb.AppendLine($"                Debug.LogWarning(\"[TableLoader] '{className}' ?곗씠???뚯씪??李얠쓣 ???놁뒿?덈떎.\");");
                sb.AppendLine($"        }}");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static void GenerateAll(TableLoaderSettings settings)
        {
            if (!Directory.Exists(settings.codeOutputPath))
                Directory.CreateDirectory(settings.codeOutputPath);

            var tableInfos = new List<(string className, string sheetName)>();

            foreach (var sheet in settings.sheets)
            {
                if (!sheet.enabled) continue;

                var csvPath = Path.Combine(settings.csvOutputPath, $"{sheet.GetClassName()}.csv");
                if (!File.Exists(csvPath))
                {
                    Debug.LogWarning($"[TableLoader] CSV ?뚯씪 ?놁쓬: {csvPath}. 癒쇱? ?ㅼ슫濡쒕뱶?섏꽭??");
                    continue;
                }

                var csv = File.ReadAllText(csvPath);
                var rows = CsvParser.Parse(csv);
                var columns = ParseSchema(rows);

                if (columns.Count == 0)
                {
                    Debug.LogWarning($"[TableLoader] '{sheet.sheetName}' ?ㅽ궎留덇? 鍮꾩뼱?덉뒿?덈떎.");
                    continue;
                }

                var className = sheet.GetClassName();
                var code = GenerateDataClass(className, columns);
                var codePath = Path.Combine(settings.codeOutputPath, $"{className}.cs");
                File.WriteAllText(codePath, code);
                Debug.Log($"[TableLoader] 肄붾뱶 ?앹꽦 ?꾨즺: {codePath}");

                tableInfos.Add((className, sheet.sheetName));
            }

            if (tableInfos.Count > 0)
            {
                var loaderCode = GenerateLoaderClass(tableInfos);
                var loaderPath = Path.Combine(settings.codeOutputPath, "TableLoaderGenerated.cs");
                File.WriteAllText(loaderPath, loaderCode);
                Debug.Log($"[TableLoader] 濡쒕뜑 肄붾뱶 ?앹꽦 ?꾨즺: {loaderPath}");
            }

            AssetDatabase.Refresh();
        }
    }
}
